version: 1.1.{build}-{branch}



image:
 - Visual Studio 2019

platform:
  - x64

stack: node 18.12.0

cache:
  - node_modules

install:
 - yarn

build: off


deploy: off

branches:
  only:
    - master


build_script:
  - cd src/app && yarn run start && cd ts && yarn run serve
deploy_script:  # скрипт развёртывания
# Конкретно шаг развертывания выполняется вот этим скриптом:
# deploy_script: # скрипт развёртывания

# https://www.appveyor.com/docs/how-to/git-push/
# https://www.appveyor.com/docs/how-to/git-push/#adding-access-token-to-credential-store
  - git config --global credential.helper store #включает кеширование учетных данных
  - git config --global user.name Tryd0g0lik
  - git config --global user.email work80@mail.ru
  # При аутентификации с помощью токена доступа `x-oauth-basic` используется в качестве заглушки пароля
  #- ps: Set-Content -Path  "$HOME/.git-credentials" -Value "https://$GITHUB_TOKEN:x-oauth-basic@github.com"  -NoNewline
  - ps: Write-Host "https://$GITHUB_TOKEN:x-oauth-basic@github.com" > "$HOME/.git-credentials" -NoNewline

  - yarn add push-dir --dir=dist --branch=master
  # --force
# Обратите внимание на последнюю строчку, она отправляет собранное приложение на github pages, где оно будет доступно по
# ссылке, которую я вам написал, а не той которую вы нашли в статье на другую тему.
