name: sse-ws_ne
on: [push, pull_request]
# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # действие проверяет содержимое хранилища, в котором
      # размещен вызывающий рабочий процесс, а не вызываемый рабочий процесс.
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: cd src/app/frontend && yarn run build:dev
      - name: Install dependencies
        run: yarn install
        
      - name: Build-frontend
        run: yarn workspace child-frontend-config run build:dev

      - name: Build-folder-BackandDb
        run: |
          mkdir -p dist/backend/db
          mkdir -p dist/backend/src/app/backend/src/serve
          mkdir -p dist/db/src/app/db/src/db
          
      - name: Build-workspace-build:dev
        run: yarn workspace child-backend-config run build:dev
        
      - name: Buil-subtree-creat-dist-backend
        run: |
          rsync -av --prune-empty-dirs --include '*.js' --exclude '*' dist/backend/src/app/backend/src/serve/ dist/backend/db/
          rsync -av --prune-empty-dirs --include '*.map' --exclude '*' dist/backend/src/app/backend/src/serve/ dist/backend/db/
      
      - name: Move db index files
        run: |
          rsync -av --prune-empty-dirs --include '*.js' --exclude '*' dist/db/src/app/db/src/db/ dist/backend/db
          rsync -av --prune-empty-dirs --include '*.map' --exclude '*' dist/db/src/app/db/src/db/ dist/backend/db
      
      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: 'dist'
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/github-pages-deploy-action@v4.4.3
        with:
            branch: gh-pages
            folder: dist
